title: "IoT autopsy"
description: "Hardware analysis, firmware reverse engineering and interface exploitation of IoT devices"
baseurl: /iot-autopsy

remote_theme: just-the-docs/just-the-docs

plugins:
  - jekyll-remote-theme
